test_sessions = [
    {
        "id": 3,
        "course_id": 3,
        "location_id": 1,
        "title": "😤 Data Structures - Section A",
        "location": "Main Library - Room 101",
        "time": "7:00 AM",
        "attendees": 15,
        "max_attendees": 25,
        "description": "Dynamic programming drill session with whiteboard practice.",
        "notes": "Warm-up problems emailed the night before.",
        "organizer": "Morgan Lee",
        "chill_level": "😤",
        "start_time": "2025-02-22T07:00:00",
        "end_time": "2025-02-22T09:30:00",
        "attendee_list": [
            "Morgan Lee (Host)",
            "Jamie F.",
            "Riley S."
        ],
        "room_type_id": 1,
        "tag_ids": [1, 4]
    },
    {
        "id": 4,
        "course_id": 4,
        "location_id": 5,
        "title": "🤓 Algorithms - Section C",
        "location": "Engineering Building - Room 305",
        "time": "3:00 PM",
        "attendees": 12,
        "max_attendees": 18,
        "description": "Greedy vs. divide-and-conquer problem showdown.",
        "organizer": "Nina Alvarez",
        "chill_level": "🤓",
        "start_time": "2025-02-23T15:00:00",
        "end_time": "2025-02-23T17:00:00",
        "attendee_list": {
            "Confirmed": 12,
            "Waitlist": 3
        },
        "room_type_id": 2,
        "tag_ids": [2]
    },
    {
        "id": 5,
        "course_id": 5,
        "location_id": 4,
        "title": "😎 Web Development - Section A",
        "location": "Student Center - Room 201",
        "time": "5:00 PM",
        "attendees": 10,
        "max_attendees": 15,
        "description": "Pair programming on responsive layout challenges.",
        "notes": "Bring a project you want feedback on.",
        "organizer": "Samira Chen",
        "chill_level": "😎",
        "start_time": "2025-02-24T17:00:00",
        "end_time": "2025-02-24T19:00:00",
        "room_type_id": 2,
        "tag_ids": [1]
    },
    {
        "id": 6,
        "course_id": 1,
        "location_id": 2,
        "title": "😎 Principles Of Database Systems - Section A",
        "location": "Main Library - Room 102",
        "time": "6:00 AM",
        "attendees": 25,
        "max_attendees": 25,
        "organizer": "Theo Grant",
        "start_time": "2025-02-21T06:00:00",
        "end_time": "2025-02-21T08:00:00",
        "room_type_id": 1,
        "tag_ids": [4]
    },
    {
        "id": 7,
        "course_id": 7,
        "location_id": 3,
        "title": "🤓 Linear Algebra - Section D",
        "location": "Main Library - Study Room A",
        "time": "1:30 PM",
        "attendees": 9,
        "max_attendees": 12,
        "description": "Eigenvalues concept review with curated problem walkthroughs.",
        "organizer": "Dr. Patel",
        "chill_level": "🤓",
        "start_time": "2025-02-25T13:30:00",
        "end_time": "2025-02-25T15:00:00",
        "room_type_id": 3,
        "tag_ids": [2]
    },
    {
        "id": 8,
        "course_id": 2,
        "location_id": 1,
        "title": "🤓 Coding 101 - Section B",
        "location": "Main Library - Room 101",
        "time": "10:00 AM",
        "attendees": 20,
        "max_attendees": 40,
        "organizer": "Workshop Team",
        "notes": "Hands-on debugging lab. Bring a failing script!",
        "room_type_id": 1,
        "tag_ids": [3]
    },
    {
        "id": 9,
        "course_id": 6,
        "location_id": 7,
        "title": "😎 Machine Learning - Section B",
        "location": "Innovation Hub - 2nd Floor Commons",
        "time": "4:00 PM",
        "attendees": 8,
        "max_attendees": 16,
        "description": "AutoML demo session featuring new tooling.",
        "organizer": "Priya Desai",
        "start_time": "2025-02-26T16:00:00",
        "end_time": "2025-02-26T17:30:00",
        "attendee_list": [
            "Priya Desai",
            "Harvey B.",
            "Ana T."
        ],
        "room_type_id": 2,
        "tag_ids": [1, 2]
    },
    {
        "id": 10,
        "course_id": 3,
        "location_id": 6,
        "title": "😤 Data Structures - Section A",
        "location": "Science Center - Lab 1",
        "time": "11:00 AM",
        "attendees": 18,
        "max_attendees": 18,
        "organizer": "Morgan Lee",
        "chill_level": "😤",
        "notes": "Lab computers reserved; arrive 10 minutes early.",
        "start_time": "2025-02-27T11:00:00",
        "end_time": "2025-02-27T13:00:00",
        "room_type_id": 3,
        "tag_ids": [2]
    }
]
